### ISSUE TITLE
debian packages

### ISSUE THREAD

**Issue by stuaxo** [nehz/pubsub#1]
I'm going to try see if I can get debian packages approved, as I use pubsub in shoebot, this ticket is to collect info.

previous discussion:   https://github.com/nehz/avalon/issues/1#issuecomment-147067236

**Comment by stuaxo** [comment]
~~This script attempts to make a package using stdeb, will see what the process is..~~

~~https://gist.github.com/stuaxo/9ea405006f389564a363~~

**Comment by stuaxo** [comment]
Better late than never, some renewed notes for next time I land on this:

Install stdeb
`$ pip3 install stdeb --user`

Command to generate deb (python3 only):
`$ python3 setup.py --command-packages=stdeb.command sdist_dsc --with-python2=False --with-python3=True bdist_deb`

TODO:  work out what needs adding to the generated debs to make them suitable for inclusion in debian.

**Comment by stuaxo** [comment]
For anyone looking at stdebizing this in the future, this works:
```$ python3 setup.py --command-packages=stdeb.command bdist_deb```

pypubsub already made a package called that got the python3-pubsub name.

I totally understand not having enough time to do packaging (it's 7 years since I opened this ticket!)

For now I'm going to switch my code to pypubsub, since they already have a debian package (even if I somewhat prefer the API of this project for simplicity.)

Hopefully someone will find this in future and be able to take it forward.

**Comment by ZhenWang-Avant** [comment]
Thanks for you efforts! 7 years already!
Hopefully I'll have some time in the future to revisit

**Comment by nehz** [comment]
Thanks for you efforts! 7 years already!
Hopefully I'll have some time in the future to revisit
