### ISSUE TITLE
GraphQL in PyPI

### ISSUE THREAD

**Issue by syrusakbary** [nehz/pubsub#4]
Hi Zhen,

I searched but I cannot find any other way for contacting you than opening a issue in Github.
I'm contributing to the GraphQL Python community and the package `graphql` in [PyPI](https://pypi.python.org/pypi/graphql) is already taken but with no contributions or ways for installing it. _It seems that you are owner_ of this package.

Would make sense transfer to us the package, or add us to maintainers so the community can install us in a easy way.

Please don't hesitate to contact me if you have any questions: me@syrusakbary.com

**Comment by nehz** [comment]
Sorry I am developing an implementation myself
